### PR TITLE
fix typos in docs

### PR DESCRIPTION
**Pull request by dsanders11**
Just fixing a handful of typos in the docs.

### CODE REVIEW

**Comment by lamiazar** [comment]
@dsanders11 Thanks for your contribution, the typos were already fixed in #50

**Comment by chicoxyzzy** [comment]
Most of these fixes make sense to me

**Comment by lamiazar** [comment]
> Most of these fixes make sense to me
yes, but I already fixed them here: #50

**Comment by lamiazar** [comment]
Sounds good, let's do that.

**Comment by chicoxyzzy** [comment]
@dsanders11 I've merged your changes in https://github.com/socketsupply/sockets.sh/pull/55 as I can't push to your branch. Thank you for you contribution!

**Pull request closed without merging**
